### PR TITLE
Support $interval promises

### PR DESCRIPTION
**Pull request by mchambaud**
Supporting $interval the same way you are currently supporting $timeout.

### CODE REVIEW

**Comment by mchambaud** [comment]
@bvaughn What do you think about merging this back into your repo?

**Comment by bvaughn** [comment]
Do you mind removing the `dist` bit from the PR? So it's source only?

**Comment by mchambaud** [comment]
I just reverted the `dist` folder

I'm currently using my branch on a customer buffered retry function and it works like a charm.

**Comment by mchambaud** [comment]
When ever you have a chance, it would be great to push this on NPM!

Thanks mate, and by the way this library is saving us some massive amount of Garbage code in our tests, wish I knew it existed earlier!

**Comment by bvaughn** [comment]
Yup, I haven't forgot. Still have a window open to this PR. Just swamped at the moment. Hit a problem running tests and building this (not sure why yet) and ran out of time looking into it. Will try to cycle back soon.

I know I recently asked you to _remove_ the `dist` contents from the PR, but if you'd like to toss up another PR with them, I'd be willing to accept and publish (just to save time) 😄

**Comment by bvaughn** [comment]
PS Glad to hear it's helping!

**Comment by mchambaud** [comment]
Not sure what's up with dist content but I can do that no problem!

**Comment by bvaughn** [comment]
Nothing's "up" with it persay. I normally don't like for PRs to have both source _and_ built/bundled/dist contents, since it muddies the waters a bit _and_ potentially causes merge conflicts if there are multiple PRs open at once.

That being said, in this case, I haven't built this project in a long time- 3 or 4 laptops ago, actually- and I'm having trouble actually _building_ it at the moment. Since I don't have time to dig into it right now (b'c of work) I thought it would save time to ask you to just re-commit the dist. :)

**Comment by mchambaud** [comment]
Perhaps we could automate the build with a CI.

**Comment by bvaughn** [comment]
If you'd like to take over that, I'd be happy to add you as a contributor so you can just push directly 😄

I'm on the React team these days. I haven't used Angular in a couple of years now, so it's hard to stay on top of projects like this.

**Comment by mchambaud** [comment]
Sure, I understand! I don't see a need for a CI right now, but I might be just do it for fun on a rainy day!

Being on the React team must be quite amazing, props to you!

**Comment by bvaughn** [comment]
I'll add you as a collaborate just in case you feel the urger 😄 

Yeah, it's great! Thank you!

**Pull request merged**
